/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        /** Upload Document */
        post: operations["upload_document_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Document Chapters
         * @description Chapters in reading order with their vocabulary counts (empty before analysis).
         */
        get: operations["list_document_chapters_api_documents__document_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Document
         * @description Detect chapters and extract vocabulary with the AI provider (runs synchronously).
         */
        post: operations["analyze_document_api_documents__document_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapter_id}/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chapter Vocabulary
         * @description The chapter's vocabulary items in the order they appear in the PDF.
         */
        get: operations["list_chapter_vocabulary_api_chapters__chapter_id__vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Learning Session
         * @description Start a batch: the next unstudied words (mode=new) or unmastered ones (mode=review).
         *
         *     A new batch is locked (409 batch_locked) until every studied word of the chapter is
         *     mastered; review them first.
         */
        post: operations["start_learning_session_api_learning_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{learning_session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Learning Session */
        get: operations["get_learning_session_api_learning_sessions__learning_session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{learning_session_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Learning Session Items
         * @description The words of the batch in display order, with their current learning status.
         */
        get: operations["list_learning_session_items_api_learning_sessions__learning_session_id__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{learning_session_id}/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Quiz
         * @description Create the batch's quiz (one question per word); calling it again returns the same quiz.
         */
        post: operations["create_quiz_api_learning_sessions__learning_session_id__quiz_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quiz/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Question
         * @description Evaluate an answer (exact → normalized → AI if needed) and update the word's progress.
         *
         *     Each question can be answered once. The response reveals the expected answer and a
         *     Turkish explanation.
         */
        post: operations["answer_question_api_quiz__question_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Progress
         * @description Word counts per status for every chapter, and whether a new batch or review can start.
         */
        get: operations["get_progress_api_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/weak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Weak Words
         * @description Weak words (longest due first) with the latest mistake and its Turkish explanation.
         *
         *     Review them with POST /api/learning-sessions using mode=review.
         */
        get: operations["list_weak_words_api_review_weak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerResultRead */
        AnswerResultRead: {
            question: components["schemas"]["QuizQuestionRead"];
            vocabulary_status: components["schemas"]["VocabularyStatus"];
            learning_session: components["schemas"]["LearningSessionRead"];
        };
        /** AnswerSubmit */
        AnswerSubmit: {
            /** Answer */
            answer: string;
        };
        /** Body_upload_document_api_documents_post */
        Body_upload_document_api_documents_post: {
            /**
             * File
             * @description Vocabulary PDF
             */
            file: string;
        };
        /** ChapterProgressRead */
        ChapterProgressRead: {
            /** Total */
            total: number;
            /** New */
            new: number;
            /** Learning */
            learning: number;
            /** Weak */
            weak: number;
            /** Mastered */
            mastered: number;
            /** Mastery Ratio */
            mastery_ratio: number;
            /** Chapter Id */
            chapter_id: number;
            /** Document Id */
            document_id: number;
            /** Chapter Number */
            chapter_number: number | null;
            /** Title */
            title: string;
            /** Can Start New Batch */
            can_start_new_batch: boolean;
            /** Can Review */
            can_review: boolean;
        };
        /** ChapterSummaryRead */
        ChapterSummaryRead: {
            /** Id */
            id: number;
            /** Chapter Number */
            chapter_number: number | null;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Source Start Page */
            source_start_page: number;
            /** Source End Page */
            source_end_page: number;
            /** Vocabulary Count */
            vocabulary_count: number;
        };
        /** DocumentAnalysisRead */
        DocumentAnalysisRead: {
            document: components["schemas"]["DocumentRead"];
            /** Chapter Count */
            chapter_count: number;
            /** Vocabulary Count */
            vocabulary_count: number;
            /** Rejected Item Count */
            rejected_item_count: number;
            /** Chapters */
            chapters: components["schemas"]["ChapterSummaryRead"][];
        };
        /** DocumentRead */
        DocumentRead: {
            /** Id */
            id: number;
            /** User Id */
            user_id: number | null;
            /** Original File Name */
            original_file_name: string;
            /** File Name */
            file_name: string;
            status: components["schemas"]["DocumentStatus"];
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Processed At */
            processed_at: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "uploaded" | "parsing" | "parsed" | "failed";
        /**
         * ErrorType
         * @enum {string}
         */
        ErrorType: "article" | "case" | "preposition" | "word_order" | "verb_conjugation" | "spelling" | "vocabulary_usage" | "meaning" | "grammar";
        /**
         * EvaluationMethod
         * @enum {string}
         */
        EvaluationMethod: "exact" | "normalized" | "rule" | "ai";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /** Version */
            version: string;
        };
        /** LearningSessionCreate */
        LearningSessionCreate: {
            /** Chapter Id */
            chapter_id: number;
            /**
             * Batch Size
             * @description Number of words to study (e.g. 5, 10 or 20).
             * @default 10
             */
            batch_size: number;
            /**
             * @description new: the chapter's next unstudied words (once the batch is unlocked); review: studied but not yet mastered words, weak ones first.
             * @default new
             */
            mode: components["schemas"]["SessionMode"];
        };
        /** LearningSessionItemRead */
        LearningSessionItemRead: {
            /** Position */
            position: number;
            status: components["schemas"]["VocabularyStatus"];
            vocabulary_item: components["schemas"]["VocabularyItemRead"];
        };
        /** LearningSessionRead */
        LearningSessionRead: {
            /** Id */
            id: number;
            /** Chapter Id */
            chapter_id: number;
            /** Chapter Title */
            chapter_title: string;
            /** Document Id */
            document_id: number;
            /** Batch Size */
            batch_size: number;
            mode: components["schemas"]["SessionMode"];
            /**
             * Item Count
             * @description Can be below batch_size for the chapter's last batch.
             */
            item_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Correct Count */
            correct_count: number;
            /** Wrong Count */
            wrong_count: number;
        };
        /**
         * MistakeRead
         * @description The learner's latest wrong answer, to explain the mistake.
         */
        MistakeRead: {
            /** Question Id */
            question_id: number;
            question_type: components["schemas"]["QuestionType"];
            /** Question */
            question: string;
            /** User Answer */
            user_answer: string | null;
            /** Expected Answer */
            expected_answer: string;
            /** Corrected Answer */
            corrected_answer: string | null;
            /** Feedback */
            feedback: string | null;
            error_type: components["schemas"]["ErrorType"] | null;
            /** Answered At */
            answered_at: string | null;
        };
        /** ProgressRead */
        ProgressRead: {
            /** Total */
            total: number;
            /** New */
            new: number;
            /** Learning */
            learning: number;
            /** Weak */
            weak: number;
            /** Mastered */
            mastered: number;
            /** Mastery Ratio */
            mastery_ratio: number;
            /** Chapters */
            chapters: components["schemas"]["ChapterProgressRead"][];
        };
        /**
         * QuestionType
         * @enum {string}
         */
        QuestionType: "german_to_turkish" | "turkish_to_german" | "fill_blank" | "sentence_translation" | "verb_conjugation" | "article" | "preposition" | "free_sentence";
        /**
         * QuizQuestionRead
         * @description A question as shown to the learner. Answer fields stay empty until it is answered.
         */
        QuizQuestionRead: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Vocabulary Item Id */
            vocabulary_item_id: number;
            question_type: components["schemas"]["QuestionType"];
            /** Question */
            question: string;
            /** User Answer */
            user_answer: string | null;
            /** Is Correct */
            is_correct: boolean | null;
            /** Score */
            score: number | null;
            /**
             * Expected Answer
             * @description Revealed only after answering.
             */
            expected_answer: string | null;
            /** Corrected Answer */
            corrected_answer: string | null;
            /**
             * Ai Feedback
             * @description Turkish explanation of the evaluation.
             */
            ai_feedback: string | null;
            error_type: components["schemas"]["ErrorType"] | null;
            evaluation_method: components["schemas"]["EvaluationMethod"] | null;
            /** Answered At */
            answered_at: string | null;
        };
        /** QuizRead */
        QuizRead: {
            /** Learning Session Id */
            learning_session_id: number;
            /** Question Count */
            question_count: number;
            /** Questions */
            questions: components["schemas"]["QuizQuestionRead"][];
        };
        /**
         * SessionMode
         * @enum {string}
         */
        SessionMode: "new" | "review";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VocabularyItemRead */
        VocabularyItemRead: {
            /** Id */
            id: number;
            /** Chapter Id */
            chapter_id: number;
            /** Order */
            order: number;
            /** German */
            german: string;
            /** Turkish */
            turkish: string;
            item_type: components["schemas"]["VocabularyItemType"];
            /** Article */
            article: string | null;
            /** Base Verb */
            base_verb: string | null;
            /** Prateritum */
            prateritum: string | null;
            /** Perfekt */
            perfekt: string | null;
            /** Preposition */
            preposition: string | null;
            /** Grammatical Case */
            grammatical_case: string | null;
            /** Example German */
            example_german: string | null;
            /** Example Turkish */
            example_turkish: string | null;
            /** Source Text */
            source_text: string | null;
            /** Source Page */
            source_page: number | null;
        };
        /**
         * VocabularyItemType
         * @enum {string}
         */
        VocabularyItemType: "word" | "noun" | "verb" | "phrase" | "expression" | "grammar_pattern";
        /**
         * VocabularyStatus
         * @enum {string}
         */
        VocabularyStatus: "new" | "learning" | "weak" | "mastered";
        /** WeakWordRead */
        WeakWordRead: {
            vocabulary_item: components["schemas"]["VocabularyItemRead"];
            progress: components["schemas"]["WordProgressRead"];
            last_mistake: components["schemas"]["MistakeRead"] | null;
        };
        /** WordProgressRead */
        WordProgressRead: {
            status: components["schemas"]["VocabularyStatus"];
            /** Seen Count */
            seen_count: number;
            /** Correct Count */
            correct_count: number;
            /** Wrong Count */
            wrong_count: number;
            /** Consecutive Correct */
            consecutive_correct: number;
            /** Mastery Score */
            mastery_score: number;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Next Review At */
            next_review_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_document_chapters_api_documents__document_id__chapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterSummaryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_document_api_documents__document_id__analyze_post: {
        parameters: {
            query?: {
                /** @description Analyze again even if the document was already analyzed. */
                force?: boolean;
            };
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentAnalysisRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapter_vocabulary_api_chapters__chapter_id__vocabulary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_learning_session_api_learning_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_learning_session_api_learning_sessions__learning_session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_learning_session_items_api_learning_sessions__learning_session_id__items_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_quiz_api_learning_sessions__learning_session_id__quiz_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learning_session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The quiz already existed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizRead"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_api_quiz__question_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                question_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerSubmit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_progress_get: {
        parameters: {
            query?: {
                /** @description Only this document's chapters. */
                document_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_weak_words_api_review_weak_get: {
        parameters: {
            query?: {
                document_id?: number | null;
                chapter_id?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeakWordRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
