"""learning session mode

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-28 15:53:18.064483+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "learning_sessions",
        sa.Column(
            "mode",
            sa.Enum("new", "review", name="sessionmode", native_enum=False, length=20),
            server_default="new",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("learning_sessions", "mode")
    # ### end Alembic commands ###
