"""quiz questions

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 15:28:45.036607+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learning_session_id", sa.Integer(), nullable=False),
        sa.Column("vocabulary_item_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "german_to_turkish",
                "turkish_to_german",
                "fill_blank",
                "sentence_translation",
                "verb_conjugation",
                "article",
                "preposition",
                "free_sentence",
                name="questiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("expected_answer", sa.Text(), nullable=False),
        sa.Column("user_answer", sa.Text(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("ai_feedback", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["learning_session_id"],
            ["learning_sessions.id"],
            name=op.f("fk_quiz_questions_learning_session_id_learning_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vocabulary_item_id"],
            ["vocabulary_items.id"],
            name=op.f("fk_quiz_questions_vocabulary_item_id_vocabulary_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
        sa.UniqueConstraint(
            "learning_session_id",
            "position",
            name=op.f("uq_quiz_questions_learning_session_id_position"),
        ),
    )
    op.create_index(
        op.f("ix_quiz_questions_vocabulary_item_id"),
        "quiz_questions",
        ["vocabulary_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_questions_vocabulary_item_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    # ### end Alembic commands ###
