"""learning sessions and vocabulary progress

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 15:15:42.056181+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chapter_id", sa.Integer(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("correct_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("wrong_count", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("batch_size > 0", name=op.f("ck_learning_sessions_batch_size_positive")),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_learning_sessions_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_sessions")),
    )
    op.create_index(
        op.f("ix_learning_sessions_chapter_id"), "learning_sessions", ["chapter_id"], unique=False
    )
    op.create_index(
        op.f("ix_learning_sessions_user_id"), "learning_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "learning_session_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("learning_session_id", sa.Integer(), nullable=False),
        sa.Column("vocabulary_item_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learning_session_id"],
            ["learning_sessions.id"],
            name=op.f("fk_learning_session_items_learning_session_id_learning_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vocabulary_item_id"],
            ["vocabulary_items.id"],
            name=op.f("fk_learning_session_items_vocabulary_item_id_vocabulary_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_session_items")),
        sa.UniqueConstraint(
            "learning_session_id",
            "position",
            name=op.f("uq_learning_session_items_learning_session_id_position"),
        ),
        sa.UniqueConstraint(
            "learning_session_id", "vocabulary_item_id", name="uq_learning_session_items_item"
        ),
    )
    op.create_index(
        op.f("ix_learning_session_items_vocabulary_item_id"),
        "learning_session_items",
        ["vocabulary_item_id"],
        unique=False,
    )
    op.create_table(
        "user_vocabulary_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("vocabulary_item_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "learning",
                "weak",
                "mastered",
                name="vocabularystatus",
                native_enum=False,
                length=20,
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("seen_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("correct_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("wrong_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("consecutive_correct", sa.Integer(), server_default="0", nullable=False),
        sa.Column("mastery_score", sa.Float(), server_default="0", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["vocabulary_item_id"],
            ["vocabulary_items.id"],
            name=op.f("fk_user_vocabulary_progress_vocabulary_item_id_vocabulary_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_vocabulary_progress")),
        sa.UniqueConstraint(
            "user_id",
            "vocabulary_item_id",
            name=op.f("uq_user_vocabulary_progress_user_id_vocabulary_item_id"),
        ),
    )
    op.create_index(
        op.f("ix_user_vocabulary_progress_vocabulary_item_id"),
        "user_vocabulary_progress",
        ["vocabulary_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_vocabulary_progress_vocabulary_item_id"),
        table_name="user_vocabulary_progress",
    )
    op.drop_table("user_vocabulary_progress")
    op.drop_index(
        op.f("ix_learning_session_items_vocabulary_item_id"), table_name="learning_session_items"
    )
    op.drop_table("learning_session_items")
    op.drop_index(op.f("ix_learning_sessions_user_id"), table_name="learning_sessions")
    op.drop_index(op.f("ix_learning_sessions_chapter_id"), table_name="learning_sessions")
    op.drop_table("learning_sessions")
    # ### end Alembic commands ###
